repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch # Raises error if a commit is done to main
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        types: [python]
        exclude: test_libs
      - id: check-merge-conflict

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        pass_filenames: false

  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        name: Ruff Lint
        args: [--fix]
      - id: ruff-format
        name: Ruff Format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
    hooks:
      - id: pyright
