[project]
name = "pyisolate"
version = "0.1.0"
description = "TODO"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=8.4.2",
]
linting = [
    'ruff',  # Used for linting
    'pyright'  # Used for type-checking
]


[tool.codespell]
skip = ".git,env*,uv.lock,package-lock.json,test_libs"
ignore-words-list = ["pyisolate"]  # Comma-separated
