[project]
name = "reyk-cli"
dynamic = ["version"]
description = "Manage isolated environment dependencies."
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["typer>=0.20.0", "tomli>=2.4.0; python_version < '3.11'"]
license = 'MIT'
license-files = ['LICENSE']

[dependency-groups]
dev = ["pytest>=8.4.2", "tomli-w>=1.2.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/reyk_cli/version.py"

[project.scripts]
reyk-cli = "reyk_cli.cli:app"

[tool.pytest.ini_options]
pythonpath = ["src"]
